# syntax=docker/dockerfile:1.2
FROM nvidia/cuda:12.2.2-devel-ubuntu22.04

# Install base packages
RUN apt update
RUN apt install -y libssl-dev curl build-essential pkg-config git python3 python3-pip
RUN pip install --upgrade pip

# Install rust with rustup
RUN curl -sSf https://sh.rustup.rs | bash -s -- -y --profile minimal
ENV PATH="/root/.cargo/bin:${PATH}"

# Install text-embeddings-inference
ENV CUDA_COMPUTE_CAP=80
ENV RUSTFLAGS="-C target-cpu=x86-64-v3"
RUN git clone https://github.com/huggingface/text-embeddings-inference /opt/text-embeddings-inference
RUN cargo install --path /opt/text-embeddings-inference/router -F candle-cuda

# Install python tools
RUN pip install ipython torch huggingface-hub transformers
RUN pip install git+https://github.com/CompendiumLabs/ziggy
RUN pip install git+https://github.com/CompendiumLabs/oneping

# Install user tools
RUN apt install -y nano screen zsh
RUN pip install nvitop
ENV SHELL="/bin/zsh"

# Install randos
ENV XH_BINDIR="/usr/local/bin"
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ducaale/xh/master/install.sh)"
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN sed -i 's/^plugins=(git)/plugins=(git zsh-autosuggestions)/' ~/.zshrc

# Keep container running
WORKDIR /root
CMD ["sleep", "infinity"]
